//
// Generated file, do not edit! Created by opp_msgtool 6.3 from messages/ControlMessage.msg.
//

#ifndef __CONTROLMESSAGE_M_H
#define __CONTROLMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class GCLUpdate;
class FlowSchedule;
class ControlMessage;
/**
 * Class generated from <tt>messages/ControlMessage.msg:4</tt> by opp_msgtool.
 * <pre>
 * message GCLUpdate
 * {
 *     int switchId;
 *     int portId;
 *     string gclData;       // GCL configuration data
 * }
 * </pre>
 */
class GCLUpdate : public ::omnetpp::cMessage
{
  protected:
    int switchId = 0;
    int portId = 0;
    omnetpp::opp_string gclData;

  private:
    void copy(const GCLUpdate& other);

  protected:
    bool operator==(const GCLUpdate&) = delete;

  public:
    GCLUpdate(const char *name=nullptr, short kind=0);
    GCLUpdate(const GCLUpdate& other);
    virtual ~GCLUpdate();
    GCLUpdate& operator=(const GCLUpdate& other);
    virtual GCLUpdate *dup() const override {return new GCLUpdate(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSwitchId() const;
    virtual void setSwitchId(int switchId);

    virtual int getPortId() const;
    virtual void setPortId(int portId);

    virtual const char * getGclData() const;
    virtual void setGclData(const char * gclData);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GCLUpdate& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GCLUpdate& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>messages/ControlMessage.msg:10</tt> by opp_msgtool.
 * <pre>
 * message FlowSchedule
 * {
 *     int flowId;
 *     int priority;
 *     int timeSlot;
 *     double expectedDelay;
 * }
 * </pre>
 */
class FlowSchedule : public ::omnetpp::cMessage
{
  protected:
    int flowId = 0;
    int priority = 0;
    int timeSlot = 0;
    double expectedDelay = 0;

  private:
    void copy(const FlowSchedule& other);

  protected:
    bool operator==(const FlowSchedule&) = delete;

  public:
    FlowSchedule(const char *name=nullptr, short kind=0);
    FlowSchedule(const FlowSchedule& other);
    virtual ~FlowSchedule();
    FlowSchedule& operator=(const FlowSchedule& other);
    virtual FlowSchedule *dup() const override {return new FlowSchedule(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getFlowId() const;
    virtual void setFlowId(int flowId);

    virtual int getPriority() const;
    virtual void setPriority(int priority);

    virtual int getTimeSlot() const;
    virtual void setTimeSlot(int timeSlot);

    virtual double getExpectedDelay() const;
    virtual void setExpectedDelay(double expectedDelay);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FlowSchedule& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FlowSchedule& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>messages/ControlMessage.msg:17</tt> by opp_msgtool.
 * <pre>
 * message ControlMessage
 * {
 *     \@customize(true);
 *     int msgType;          // Message type
 *     double timestamp;
 * 
 *     GCLUpdate gclUpdate;
 *     FlowSchedule flowSchedule;
 * }
 * </pre>
 *
 * ControlMessage_Base is only useful if it gets subclassed, and ControlMessage is derived from it.
 * The minimum code to be written for ControlMessage is the following:
 *
 * <pre>
 * class ControlMessage : public ControlMessage_Base
 * {
 *   private:
 *     void copy(const ControlMessage& other) { ... }

 *   public:
 *     ControlMessage(const char *name=nullptr, short kind=0) : ControlMessage_Base(name,kind) {}
 *     ControlMessage(const ControlMessage& other) : ControlMessage_Base(other) {copy(other);}
 *     ControlMessage& operator=(const ControlMessage& other) {if (this==&other) return *this; ControlMessage_Base::operator=(other); copy(other); return *this;}
 *     virtual ControlMessage *dup() const override {return new ControlMessage(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from ControlMessage_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(ControlMessage)
 * </pre>
 */
class ControlMessage_Base : public ::omnetpp::cMessage
{
  protected:
    int msgType = 0;
    double timestamp = 0;
    GCLUpdate gclUpdate;
    FlowSchedule flowSchedule;

  private:
    void copy(const ControlMessage_Base& other);

  protected:
    bool operator==(const ControlMessage_Base&) = delete;
    // make constructors protected to avoid instantiation
    ControlMessage_Base(const char *name=nullptr, short kind=0);
    ControlMessage_Base(const ControlMessage_Base& other);
    // make assignment operator protected to force the user override it
    ControlMessage_Base& operator=(const ControlMessage_Base& other);

  public:
    virtual ~ControlMessage_Base();
    virtual ControlMessage_Base *dup() const override {throw omnetpp::cRuntimeError("You forgot to manually add a dup() function to class ControlMessage");}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getMsgType() const;
    virtual void setMsgType(int msgType);

    virtual double getTimestamp() const;
    virtual void setTimestamp(double timestamp);

    virtual const GCLUpdate& getGclUpdate() const;
    virtual GCLUpdate& getGclUpdateForUpdate() { return const_cast<GCLUpdate&>(const_cast<ControlMessage_Base*>(this)->getGclUpdate());}
    virtual void setGclUpdate(const GCLUpdate& gclUpdate);

    virtual const FlowSchedule& getFlowSchedule() const;
    virtual FlowSchedule& getFlowScheduleForUpdate() { return const_cast<FlowSchedule&>(const_cast<ControlMessage_Base*>(this)->getFlowSchedule());}
    virtual void setFlowSchedule(const FlowSchedule& flowSchedule);
};


namespace omnetpp {

template<> inline GCLUpdate *fromAnyPtr(any_ptr ptr) { return check_and_cast<GCLUpdate*>(ptr.get<cObject>()); }
template<> inline FlowSchedule *fromAnyPtr(any_ptr ptr) { return check_and_cast<FlowSchedule*>(ptr.get<cObject>()); }
template<> inline ControlMessage_Base *fromAnyPtr(any_ptr ptr) { return check_and_cast<ControlMessage_Base*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CONTROLMESSAGE_M_H

