//
// Generated file, do not edit! Created by opp_msgtool 6.3 from messages/FlowPacket.msg.
//

#ifndef __FLOWPACKET_M_H
#define __FLOWPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class FlowPacket;
/**
 * Class generated from <tt>messages/FlowPacket.msg:4</tt> by opp_msgtool.
 * <pre>
 * packet FlowPacket
 * {
 *     int flowId;
 *     int srcNode;
 *     int dstNode;
 *     int pcp;              // Priority Code Point (0-7)
 *     int qfi;              // QoS Flow Identifier
 *     int drbId;            // Data Radio Bearer ID
 *     int srcMacAddress;    // Source MAC address
 *     int dstMacAddress;    // Destination MAC address
 *     int ethertype;        // Ethernet type
 *     int vlanId;           // VLAN ID
 *     int size;             // Packet size in bytes
 *     double tstart;        // Start time
 *     double pdb;           // Per-stream Delay Bound
 *     double arrivalTime;   // Arrival time at gateway
 *     double deadline;      // Deadline for this packet
 *     double wirelessDelay; // Wireless transmission delay
 *     double jitter;        // Jitter
 *     int hopCount;         // Number of hops traversed
 *     bool isScheduled;     // Whether scheduled by OAFS
 *     int assignedQueue;    // Assigned queue priority
 *     int assignedSlot;     // Assigned time slot
 * }
 * </pre>
 */
class FlowPacket : public ::omnetpp::cPacket
{
  protected:
    int flowId = 0;
    int srcNode = 0;
    int dstNode = 0;
    int pcp = 0;
    int qfi = 0;
    int drbId = 0;
    int srcMacAddress = 0;
    int dstMacAddress = 0;
    int ethertype = 0;
    int vlanId = 0;
    int size = 0;
    double tstart = 0;
    double pdb = 0;
    double arrivalTime = 0;
    double deadline = 0;
    double wirelessDelay = 0;
    double jitter = 0;
    int hopCount = 0;
    bool isScheduled_ = false;
    int assignedQueue = 0;
    int assignedSlot = 0;

  private:
    void copy(const FlowPacket& other);

  protected:
    bool operator==(const FlowPacket&) = delete;

  public:
    FlowPacket(const char *name=nullptr, short kind=0);
    FlowPacket(const FlowPacket& other);
    virtual ~FlowPacket();
    FlowPacket& operator=(const FlowPacket& other);
    virtual FlowPacket *dup() const override {return new FlowPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getFlowId() const;
    virtual void setFlowId(int flowId);

    virtual int getSrcNode() const;
    virtual void setSrcNode(int srcNode);

    virtual int getDstNode() const;
    virtual void setDstNode(int dstNode);

    virtual int getPcp() const;
    virtual void setPcp(int pcp);

    virtual int getQfi() const;
    virtual void setQfi(int qfi);

    virtual int getDrbId() const;
    virtual void setDrbId(int drbId);

    virtual int getSrcMacAddress() const;
    virtual void setSrcMacAddress(int srcMacAddress);

    virtual int getDstMacAddress() const;
    virtual void setDstMacAddress(int dstMacAddress);

    virtual int getEthertype() const;
    virtual void setEthertype(int ethertype);

    virtual int getVlanId() const;
    virtual void setVlanId(int vlanId);

    virtual int getSize() const;
    virtual void setSize(int size);

    virtual double getTstart() const;
    virtual void setTstart(double tstart);

    virtual double getPdb() const;
    virtual void setPdb(double pdb);

    virtual double getArrivalTime() const;
    virtual void setArrivalTime(double arrivalTime);

    virtual double getDeadline() const;
    virtual void setDeadline(double deadline);

    virtual double getWirelessDelay() const;
    virtual void setWirelessDelay(double wirelessDelay);

    virtual double getJitter() const;
    virtual void setJitter(double jitter);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);

    virtual bool isScheduled() const;
    virtual void setIsScheduled(bool isScheduled);

    virtual int getAssignedQueue() const;
    virtual void setAssignedQueue(int assignedQueue);

    virtual int getAssignedSlot() const;
    virtual void setAssignedSlot(int assignedSlot);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FlowPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FlowPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline FlowPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<FlowPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __FLOWPACKET_M_H

